# Generated by Django 5.0.7 on 2024-08-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('numero_client', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
                ('addresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='Categorie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='quantite',
            new_name='quantite_produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='code',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='libelle',
        ),
        migrations.AddField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='libelle_produit',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('code_commande', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('libelle_commande', models.CharField(max_length=15)),
                ('quantite_commande', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_commande', models.DateField(auto_now=True)),
                ('Clients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_commande.client')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('code_livraison', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('libelle_livraison', models.CharField(max_length=15)),
                ('quantite_livraison', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_livraison', models.DateTimeField(auto_now=True)),
                ('Commande', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_commande.commande')),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_commande.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
