# Generated by Django 5.0.7 on 2024-08-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commande', '0002_client_remove_produit_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='Clients',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='Commande',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='Produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='code_produit',
            new_name='code',
        ),
        migrations.AddField(
            model_name='produit',
            name='Categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_commande.categorie'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
