# Generated by Django 5.0.7 on 2024-08-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commande', '0003_categorie_remove_commande_clients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='libelle_produit',
            new_name='libelle',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prix_unitaire',
            new_name='pu',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='quantite_produit',
            new_name='qte',
        ),
        migrations.AlterField(
            model_name='produit',
            name='Categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commande.categorie'),
        ),
    ]
